name: Release the nuget
on: 
 push:
   branches:
    - main
   paths-ignore: 
    - '**.md'
env:
  APP_PATH : 'src/TenantPlugIn/TenantPlugIn.csproj'
  PUBLISH_PATH: ./publish

jobs:
  Build:
    runs-on: windows-latest
    steps:
     - name : check out
       uses: actions/checkout@v4.1.7
     - name : setup Dotnet
       run: | 
        dotnet build $APP_PATH -c release -o $PUBLISH_PATH  
        dir $PUBLISH_PATH
     - name: Creating release
       uses: ncipollo/release-action@v1
       with:
          artifacts: $PUBLISH_PATH
           
    
 
