name: Release the nuget
on: 
 push:
   tags:
     - "v[0-9]+.[0-9]+.[0-9]+"
     - "[0-9]+.[0-9]+.[0-9]+"
     
env:
  APP_PATH : src/TenantPlugIn/TenantPlugIn.csproj
  PUBLISH_PATH: ./publish
  PROJECT_NAME: TenantPlugIn
  PROJECT_PATH:  src/TenantPlugIn
permissions: 
  packages: write
  
jobs:
  Build:
    runs-on: windows-latest
    steps:
     - name : check out
       uses: actions/checkout@v4.1.7
     - name : setup Dotnet
       run: | 
        dotnet build ${{env.APP_PATH}} -c release -o ${{env.PUBLISH_PATH}}  
        dir ${{env.PUBLISH_PATH}} 
     - name: Pack
       run: dotnet pack ${{env.APP_PATH}} -c Release -p:PackageVersion=${{ github.ref_name }}
     
     - name : display the content of the release folder
       run : ls ${{env.PROJECT_PATH}}/bin/Release

     - name: Push to  github registry
       #run: dotnet nuget push src/PersonneClassLibrairy/PersonneClassLibrairy/bin/Release/PersonneClassLibrairy.${{ github.ref_name }}.nupkg -s https://api.nuget.org/v3/index.json -k ${{env.GITHUB_TOKEN}} 
       run: dotnet nuget push ${{env.PROJECT_PATH}}/bin/Release/${{env.PROJECT_NAME}}.${{ github.ref_name }}.nupkg -k ${{env.NUGET_API_KEY}}  
       env:
         NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
         
           
    
 
