name: Release the nuget
on: 
 push:
   tags:
     - "v[0-9]+.[0-9]+.[0-9]+"
     - "[0-9]+.[0-9]+.[0-9]+"
     
env:
  APP_PATH : src/TenantPlugIn/TenantPlugIn.csproj
  PUBLISH_PATH: ./publish

jobs:
  Build:
    runs-on: windows-latest
    steps:
     - name : check out
       uses: actions/checkout@v4.1.7
     - name : setup Dotnet
       run: | 
        dotnet build ${{env.APP_PATH}} -c release -o ${{env.PUBLISH_PATH}}  
        dir ${{env.PUBLISH_PATH}} 
     - name: Creating release
       uses: ncipollo/release-action@v1
       env:
         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
       with:
          artifacts: ${{env.PUBLISH_PATH}}
          omitBody: true 
          tag_name: ${{github.ref}}
          release_name: Release${{github.ref}}
          draft: false
          prerelease: true
           
    
 
