name: Release the nuget
on: 
 push:
   branches:
    - main
   paths-ignore: 
    - '**.md'
jobs:
  Build:
    runs-on: windows-lastest
    steps:
     - name : check out
       uses: actions/checkout@v4.1.7
     - name : setup Dotnet
       run: | 
        dotnet build src/TenantPlugIn/TenantPlugIn.csproj -c release -o ./publish
        dir ./publish 
       
  
 
